#!/usr/bin/env bash
# SafeMe Android toolchain bootstrap — IDEMPOTENT.
# Re-creates everything that evaporates on sandbox snapshot/restore:
#   swap (kernel state, never persists), JDKs, Android SDK, Gradle caches
#   (all under ~/.cache, excluded from snapshots by design).
# What DOES persist and is reused: the SafeMe repo + git history at ~/SafeMe.
# Location-independent: resolves its own dir for env.sh/verify.sh, so the
# live copy (~/androenv) and the versioned mirror (SafeMe/tools/sandbox)
# are interchangeable.
# Usage:  bash ~/androenv/bootstrap.sh
#         source ~/androenv/env.sh   (or let verify.sh do it)
set -u
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
ROOT=/home/user/.cache/androenv
GH=/home/user/.cache/gradle-home
SDK=$ROOT/android-sdk
JDK17=$ROOT/jdk
JDK25=$ROOT/jdk25
SDKM=$SDK/cmdline-tools/latest/bin/sdkmanager
JDK17_URL="https://api.adoptium.net/v3/binary/latest/17/ga/linux/x64/jdk/hotspot/normal/eclipse"
JDK25_URL="https://api.adoptium.net/v3/binary/latest/25/ga/linux/x64/jdk/hotspot/normal/eclipse"
CMDTOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip"

ok()   { echo "[bootstrap] OK: $*"; }
step() { echo "[bootstrap] ... $*"; }
warn() { echo "[bootstrap] WARN: $*" >&2; }

mkdir -p "$ROOT" "$GH"

# ---- 1. swap (2 GB box cannot link AGP+Kotlin without it) ----
if swapon --show 2>/dev/null | grep -q /swapfile; then
    ok "swap already active ($(free -m | awk '/^Swap/{print $2}') MB)"
else
    step "enabling 3 GB swapfile (needs sudo)..."
    if sudo -n true 2>/dev/null; then
        sudo swapoff /swapfile 2>/dev/null || true
        sudo fallocate -l 3G /swapfile \
            && sudo chmod 600 /swapfile \
            && sudo mkswap /swapfile >/dev/null \
            && sudo swapon /swapfile \
            && ok "swap active ($(free -m | awk '/^Swap/{print $2}') MB)" \
            || warn "swapon failed — build may OOM; re-run this script"
    else
        warn "no passwordless sudo — cannot enable swap; build may OOM"
    fi
fi

# ---- 2. JDKs (project targets Java 25 bytecode; 17 kept as fallback) ----
ensure_jdk() {
    local dir=$1 url=$2 want=$3
    if [ -x "$dir/bin/java" ] && "$dir/bin/java" -version 2>&1 | grep -q "version \"$want"; then
        ok "JDK $want present"
        return
    fi
    step "downloading JDK $want..."
    curl -fSL --retry 3 -o "$ROOT/jdk$want.tar.gz" "$url" || { warn "JDK $want download failed"; return 1; }
    rm -rf "$dir" && mkdir -p "$dir"
    tar -xzf "$ROOT/jdk$want.tar.gz" -C "$dir" --strip-components=1 && rm -f "$ROOT/jdk$want.tar.gz"
    ok "JDK $want installed ($("$dir/bin/java" -version 2>&1 | head -1))"
}
ensure_jdk "$JDK25" "$JDK25_URL" "25" || exit 1
ensure_jdk "$JDK17" "$JDK17_URL" "17" || warn "JDK 17 missing (non-fatal, 25 is the runner)"

# ---- 3. Android SDK ----
export JAVA_HOME=$JDK25 PATH="$JDK25/bin:$PATH" ANDROID_HOME=$SDK ANDROID_SDK_ROOT=$SDK
if [ -x "$SDKM" ]; then
    ok "cmdline-tools present"
else
    step "downloading cmdline-tools..."
    curl -fSL --retry 3 -o "$ROOT/cmdtools.zip" "$CMDTOOLS_URL" || exit 1
    mkdir -p "$SDK/cmdline-tools"
    rm -rf "$SDK/cmdline-tools/latest"
    unzip -q "$ROOT/cmdtools.zip" -d "$SDK/cmdline-tools" \
        && mv "$SDK/cmdline-tools/cmdline-tools" "$SDK/cmdline-tools/latest" \
        && rm -f "$ROOT/cmdtools.zip" && ok "cmdline-tools installed"
fi
step "accepting SDK licenses..."
yes | "$SDKM" --sdk_root="$SDK" --licenses >/dev/null 2>&1 || true
need=""
for p in "platform-tools" "platforms;android-36" "build-tools;36.0.0"; do
    case $p in
        platform-tools)      [ -x "$SDK/platform-tools/adb" ]      || need="$need $p" ;;
        platforms*)          [ -f "$SDK/platforms/android-36/android.jar" ] || need="$need $p" ;;
        build-tools*)        [ -d "$SDK/build-tools/36.0.0" ]      || need="$need $p" ;;
    esac
done
if [ -z "$need" ]; then
    ok "SDK packages present (platform-tools, android-36, build-tools 36.0.0)"
else
    step "installing:$need"
    # shellcheck disable=SC2086
    "$SDKM" --sdk_root="$SDK" $need </dev/null 2>&1 | tail -1 || exit 1
    ok "SDK packages installed"
fi

# ---- 4. project wiring (repo itself persists; these bits don't) ----
printf 'sdk.dir=%s\n' "$SDK" > /home/user/SafeMe/local.properties
chmod +x /home/user/SafeMe/gradlew
ok "local.properties + gradlew wired"

# ---- 5. env file for shells (next to this script) ----
cat > "$SCRIPT_DIR/env.sh" <<EOF
# Generated by bootstrap.sh — source before running gradle.
export JAVA_HOME=$JDK25
export ANDROID_HOME=$SDK
export ANDROID_SDK_ROOT=$SDK
export GRADLE_USER_HOME=$GH
export PATH="\$JAVA_HOME/bin:\$PATH"
EOF
ok "env file written"

# ---- 6. repo config that snapshots drop (.git/config is excluded) ----
if [ -d /home/user/SafeMe/.git ]; then
    if git -C /home/user/SafeMe remote get-url origin >/dev/null 2>&1; then
        ok "origin remote present"
    elif git -C /home/user/SafeMe remote add origin https://github.com/browseros247-dev/SafeMe.git 2>/dev/null; then
        ok "origin remote restored"
    else
        warn "could not ensure origin remote"
    fi
    if git -C /home/user/SafeMe config user.name >/dev/null 2>&1 \
        && git -C /home/user/SafeMe config user.email >/dev/null 2>&1; then
        ok "git identity present"
    else
        warn "git identity missing (wiped with .git/config) — commits will fail until set:"
        warn "  git -C ~/SafeMe config user.name 'Your Name' && git -C ~/SafeMe config user.email 'you@example.com'"
    fi
fi

echo "[bootstrap] DONE. Verify with: bash \"$SCRIPT_DIR/verify.sh\""
