# Generated by bootstrap.sh — source before running gradle.
export JAVA_HOME=/home/user/.cache/androenv/jdk25
export ANDROID_HOME=/home/user/.cache/androenv/android-sdk
export ANDROID_SDK_ROOT=/home/user/.cache/androenv/android-sdk
export GRADLE_USER_HOME=/home/user/.cache/gradle-home
export PATH="$JAVA_HOME/bin:$PATH"
